/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_Main
 * Method:    WGPUCreateInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_Main_WGPUCreateInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Main
 * Method:    WGPUInstanceRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_WGPUInstanceRelease
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
