package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferUsage {
    static final int None  =  0x0;
    static final int MapRead  =  0x1;
    static final int MapWrite  =  0x2;
    static final int CopySrc  =  0x4;
    static final int CopyDst  =  0x8;
    static final int Index  =  0x10;
    static final int Vertex  =  0x20;
    static final int Uniform  =  0x40;
    static final int Storage  =  0x80;
    static final int Indirect  =  0x100;
    static final int QueryResolve  =  0x200;
}