package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUHeapProperty {
    static final int Undefined  =  0x0;
    static final int DeviceLocal  =  0x1;
    static final int HostVisible  =  0x2;
    static final int HostCoherent  =  0x4;
    static final int HostUncached  =  0x8;
    static final int HostCached  =  0x10;
}