package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUHeapProperty implements EnumMapper.IntegerEnum {
    Undefined ( 0x0 ),
    DeviceLocal ( 0x1 ),
    HostVisible ( 0x2 ),
    HostCoherent ( 0x4 ),
    HostUncached ( 0x8 ),
    HostCached ( 0x10 );

	private final int value;

	WGPUHeapProperty(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}