package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUColorWriteMask implements EnumMapper.IntegerEnum {
    None ( 0x0 ),
    Red ( 0x1 ),
    Green ( 0x2 ),
    Blue ( 0x4 ),
    Alpha ( 0x8 ),
    All ( 0xf );

	private final int value;

	WGPUColorWriteMask(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}