package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureUsage {
    static final int None  =  0x0;
    static final int CopySrc  =  0x1;
    static final int CopyDst  =  0x2;
    static final int TextureBinding  =  0x4;
    static final int StorageBinding  =  0x8;
    public static final int RenderAttachment  =  0x10;
    static final int TransientAttachment  =  0x20;
    static final int StorageAttachment  =  0x40;
}