package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUFeatureName implements EnumMapper.IntegerEnum {
    Undefined ( 0x0 ),
    DepthClipControl ( 0x1 ),
    Depth32FloatStencil8 ( 0x2 ),
    TimestampQuery ( 0x3 ),
    TextureCompressionBC ( 0x4 ),
    TextureCompressionETC2 ( 0x5 ),
    TextureCompressionASTC ( 0x6 ),
    IndirectFirstInstance ( 0x7 ),
    ShaderF16 ( 0x8 ),
    RG11B10UfloatRenderable ( 0x9 ),
    BGRA8UnormStorage ( 0xa ),
    Float32Filterable ( 0xb ),
    DawnInternalUsages ( 0x3ea ),
    DawnMultiPlanarFormats ( 0x3eb ),
    DawnNative ( 0x3ec ),
    ChromiumExperimentalTimestampQueryInsidePasses ( 0x3ee ),
    ImplicitDeviceSynchronization ( 0x3ef ),
    SurfaceCapabilities ( 0x3f0 ),
    TransientAttachments ( 0x3f1 ),
    MSAARenderToSingleSampled ( 0x3f2 ),
    DualSourceBlending ( 0x3f3 ),
    D3D11MultithreadProtected ( 0x3f4 ),
    ANGLETextureSharing ( 0x3f5 ),
    ChromiumExperimentalSubgroups ( 0x3f6 ),
    ChromiumExperimentalSubgroupUniformControlFlow ( 0x3f7 ),
    PixelLocalStorageCoherent ( 0x3f9 ),
    PixelLocalStorageNonCoherent ( 0x3fa ),
    Unorm16TextureFormats ( 0x3fb ),
    Snorm16TextureFormats ( 0x3fc ),
    MultiPlanarFormatExtendedUsages ( 0x3fd ),
    MultiPlanarFormatP010 ( 0x3fe ),
    HostMappedPointer ( 0x3ff ),
    MultiPlanarRenderTargets ( 0x400 ),
    MultiPlanarFormatNv12a ( 0x401 ),
    FramebufferFetch ( 0x402 ),
    BufferMapExtendedUsages ( 0x403 ),
    AdapterPropertiesMemoryHeaps ( 0x404 ),
    AdapterPropertiesD3D ( 0x405 ),
    AdapterPropertiesVk ( 0x406 ),
    R8UnormStorage ( 0x407 ),
    FormatCapabilities ( 0x408 ),
    DrmFormatCapabilities ( 0x409 ),
    Norm16TextureFormats ( 0x40a ),
    MultiPlanarFormatNv16 ( 0x40b ),
    MultiPlanarFormatNv24 ( 0x40c ),
    MultiPlanarFormatP210 ( 0x40d ),
    MultiPlanarFormatP410 ( 0x40e ),
    SharedTextureMemoryVkDedicatedAllocation ( 0x44c ),
    SharedTextureMemoryAHardwareBuffer ( 0x44d ),
    SharedTextureMemoryDmaBuf ( 0x44e ),
    SharedTextureMemoryOpaqueFD ( 0x44f ),
    SharedTextureMemoryZirconHandle ( 0x450 ),
    SharedTextureMemoryDXGISharedHandle ( 0x451 ),
    SharedTextureMemoryD3D11Texture2D ( 0x452 ),
    SharedTextureMemoryIOSurface ( 0x453 ),
    SharedTextureMemoryEGLImage ( 0x454 ),
    SharedFenceVkSemaphoreOpaqueFD ( 0x4b0 ),
    SharedFenceVkSemaphoreSyncFD ( 0x4b1 ),
    SharedFenceVkSemaphoreZirconHandle ( 0x4b2 ),
    SharedFenceDXGISharedHandle ( 0x4b3 ),
    SharedFenceMTLSharedEvent ( 0x4b4 ),
    SharedBufferMemoryD3D12Resource ( 0x4b5 ),
    StaticSamplers ( 0x4b6 ),
    YCbCrVulkanSamplers ( 0x4b7 ),
    ShaderModuleCompilationOptions ( 0x4b8 ),
    DawnLoadResolveTexture ( 0x4b9 );

	private final int value;

	WGPUFeatureName(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}