package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUWGSLFeatureName {
    static final int Undefined  =  0x0;
     /* this is interesting */
    static final int ReadonlyAndReadwriteStorageTextures  =  0x1;
    static final int Packed4x8IntegerDotProduct  =  0x2;
    static final int UnrestrictedPointerParameters  =  0x3;
    static final int PointerCompositeAccess  =  0x4;
    static final int ChromiumTestingUnimplemented  =  0x3e8;
    static final int ChromiumTestingUnsafeExperimental  =  0x3e9;
    static final int ChromiumTestingExperimental  =  0x3ea;
    static final int ChromiumTestingShippedWithKillswitch  =  0x3eb;
    static final int ChromiumTestingShipped  =  0x3ec;
}