package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUShaderStage {
    static final int None  =  0x0;
    static final int Vertex  =  0x1;
    static final int Fragment  =  0x2;
    static final int Compute  =  0x4;
}