package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUColorWriteMask {
    static final int None  =  0x0;
    static final int Red  =  0x1;
    static final int Green  =  0x2;
    static final int Blue  =  0x4;
    static final int Alpha  =  0x8;
    static final int All  =  0xf;
}