package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUBufferUsage implements EnumMapper.IntegerEnum {
    None ( 0x0 ),
    MapRead ( 0x1 ),
    MapWrite ( 0x2 ),
    CopySrc ( 0x4 ),
    CopyDst ( 0x8 ),
    Index ( 0x10 ),
    Vertex ( 0x20 ),
    Uniform ( 0x40 ),
    Storage ( 0x80 ),
    Indirect ( 0x100 ),
    QueryResolve ( 0x200 );

	private final int value;

	WGPUBufferUsage(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}