package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUTextureUsage implements EnumMapper.IntegerEnum {
    None ( 0x0 ),
    CopySrc ( 0x1 ),
    CopyDst ( 0x2 ),
    TextureBinding ( 0x4 ),
    StorageBinding ( 0x8 ),
    RenderAttachment ( 0x10 ),
    TransientAttachment ( 0x20 ),
    StorageAttachment ( 0x40 );

	private final int value;

	WGPUTextureUsage(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}