package com.monstrous.wgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUChainedStruct extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> next = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Struct.Enum<WGPUSType> sType = new Struct.Enum<>(WGPUSType.class);

    protected WGPUChainedStruct(){}


    @Deprecated
    public WGPUChainedStruct(Runtime runtime){
        super(runtime);
    }

    /**
     * Creates this struct on the java heap.
     * In general, this should <b>not</b> be used because these structs
     * cannot be directly passed into native code.
     */
    public static WGPUChainedStruct createHeap(){
        return new WGPUChainedStruct();
    }

    /**
     * Creates this struct in direct memory.
     * This is how most structs should be created (unless, they
     * are members of a nothing struct)
     *
     * @see WgpuJavaStruct#useDirectMemory
     */
    public static WGPUChainedStruct createDirect(){
        var struct = new WGPUChainedStruct();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNext(){
        return next;
    }

    public void setNext(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.next.set(WgpuJava.createNullPointer());
        } else {
            this.next.set(x);
        }
    }

    public WGPUSType getSType(){
        return sType.get();
    }

    public void setSType(WGPUSType x){
        this.sType.set(x);
    }

}