package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUSurfaceGetCurrentTextureStatus {
    Success,
    Timeout,
    Outdated,
    Lost,
    OutOfMemory,
    DeviceLost,
    Error,
}