package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUWGSLFeatureName implements EnumMapper.IntegerEnum {
    Undefined ( 0x0 ),
     /* this is interesting */
    ReadonlyAndReadwriteStorageTextures ( 0x1 ),
    Packed4x8IntegerDotProduct ( 0x2 ),
    UnrestrictedPointerParameters ( 0x3 ),
    PointerCompositeAccess ( 0x4 ),
    ChromiumTestingUnimplemented ( 0x3e8 ),
    ChromiumTestingUnsafeExperimental ( 0x3e9 ),
    ChromiumTestingExperimental ( 0x3ea ),
    ChromiumTestingShippedWithKillswitch ( 0x3eb ),
    ChromiumTestingShipped ( 0x3ec );

	private final int value;

	WGPUWGSLFeatureName(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}