package com.monstrous.wgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
import jnr.ffi.util.EnumMapper;

public enum WGPUShaderStage implements EnumMapper.IntegerEnum {
    None ( 0x0 ),
    Vertex ( 0x1 ),
    Fragment ( 0x2 ),
    Compute ( 0x4 );

	private final int value;

	WGPUShaderStage(int value) {this.value = value;}

	@Override
	public int intValue() {return value;} // mapping function
}